/* eslint-disable */
/* global WebImporter */
/**
 * Parser for article-header. Base block: article-header.
 * Source: https://semiconductor.samsung.com/kr/news-events/news/samsung-electronics-begins-shipment-of-industry-first-hbm4e-samples/
 * Instance selector: section.AR02_article-header__header
 *
 * Block contract (see blocks/article-header/article-header.js):
 *   row 1: eyebrow category text (e.g. "뉴스")
 *   row 2: article title (heading)
 *   row 3: publish date text (e.g. "2026년 05월 28일")
 * The social-share control row is generated by the block itself, so the parser
 * emits ONLY the authorable content (eyebrow, title, date) — never the share buttons.
 *
 * Source notes:
 *   eyebrow  -> .AR02_article-header__eyebrow
 *   title    -> h1.AR02_article-header__title
 *   date     -> time.AR02_article-header-page__header_time
 */
export default function parse(element, { document }) {
  const eyebrowEl = element.querySelector('.AR02_article-header__eyebrow');
  const titleEl = element.querySelector('.AR02_article-header__title, h1');
  const dateEl = element.querySelector(
    'time.AR02_article-header-page__header_time, time',
  );

  const eyebrowText = eyebrowEl ? eyebrowEl.textContent.trim() : '';
  const titleText = titleEl ? titleEl.textContent.trim() : '';
  const dateText = dateEl ? dateEl.textContent.trim() : '';

  // Empty-block guard: a header without a title is not meaningful.
  if (!titleText && !eyebrowText) {
    element.replaceWith(...element.childNodes);
    return;
  }

  const cells = [];

  // Row 1: eyebrow
  const eyebrow = document.createElement('p');
  eyebrow.textContent = eyebrowText;
  cells.push([eyebrow]);

  // Row 2: title (as a heading so the block can keep it as h1)
  const title = document.createElement('h1');
  title.textContent = titleText;
  cells.push([title]);

  // Row 3: publish date (preserve the semantic <time> element)
  const time = document.createElement('time');
  time.textContent = dateText;
  cells.push([time]);

  const block = WebImporter.Blocks.createBlock(document, { name: 'article-header', cells });
  element.replaceWith(block);
}
