/**
 * Article header for the news-article template.
 * Migrated from semiconductor.samsung.com/kr/news-events/news.
 *
 * Authored content (one row per item, in order):
 *   row 1: eyebrow category text (e.g. "뉴스")
 *   row 2: article title (heading)
 *   row 3: publish date text (e.g. "2026년 05월 28일")
 *
 * The social-share control row is generated by this block (Facebook, X,
 * LinkedIn, email, copy-URL) so authors do not have to maintain it.
 */

const SHARE_LABELS = {
  facebook: '페이스북',
  x: 'X',
  linkedin: '링크드인',
  email: '이메일로 공유',
  copy: '이 URL 복사',
};

function buildShare(title) {
  const pageUrl = window.location.href;
  const list = document.createElement('ul');
  list.className = 'article-header-sns';

  const addItem = (cls, label, el) => {
    const li = document.createElement('li');
    el.className = `article-header-sns-${cls}`;
    el.setAttribute('aria-label', label);
    li.append(el);
    list.append(li);
  };

  const fb = document.createElement('a');
  fb.href = `https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(pageUrl)}`;
  fb.target = '_blank';
  fb.rel = 'noopener';
  addItem('facebook', SHARE_LABELS.facebook, fb);

  const x = document.createElement('a');
  x.href = `https://twitter.com/intent/tweet?url=${encodeURIComponent(pageUrl)}&text=${encodeURIComponent(title)}`;
  x.target = '_blank';
  x.rel = 'noopener';
  addItem('x', SHARE_LABELS.x, x);

  const ln = document.createElement('a');
  ln.href = `https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(pageUrl)}`;
  ln.target = '_blank';
  ln.rel = 'noopener';
  addItem('linkedin', SHARE_LABELS.linkedin, ln);

  const mail = document.createElement('a');
  mail.href = `mailto:?subject=${encodeURIComponent(title)}&body=${encodeURIComponent(pageUrl)}`;
  addItem('email', SHARE_LABELS.email, mail);

  const copy = document.createElement('button');
  copy.type = 'button';
  copy.addEventListener('click', async () => {
    try {
      await navigator.clipboard.writeText(pageUrl);
      copy.classList.add('article-header-sns-copied');
      setTimeout(() => copy.classList.remove('article-header-sns-copied'), 1500);
    } catch (e) {
      // clipboard unavailable; no-op
    }
  });
  addItem('copy', SHARE_LABELS.copy, copy);

  return list;
}

export default function decorate(block) {
  const rows = [...block.children];
  const eyebrow = rows[0];
  const titleRow = rows[1];
  const dateRow = rows[2];

  if (eyebrow) eyebrow.className = 'article-header-eyebrow';

  let titleText = '';
  if (titleRow) {
    titleRow.className = 'article-header-title';
    titleText = titleRow.textContent.trim();
    // promote to an h1 if the author only typed text
    if (!titleRow.querySelector('h1, h2, h3')) {
      const h1 = document.createElement('h1');
      h1.textContent = titleText;
      titleRow.textContent = '';
      titleRow.append(h1);
    }
  }

  if (dateRow) {
    dateRow.className = 'article-header-date';
    const txt = dateRow.textContent.trim();
    if (!dateRow.querySelector('time')) {
      const time = document.createElement('time');
      time.textContent = txt;
      dateRow.textContent = '';
      dateRow.append(time);
    }
  }

  // Insert share controls between the title and the date, matching the source.
  const share = buildShare(titleText || document.title);
  if (dateRow) block.insertBefore(share, dateRow);
  else block.append(share);
}
